export const ADD_INGRIDIENTS = 'ADD_INGRIDIENTS';
export const GET_INGRIDIENTS = 'GET_INGRIDIENTS';
export const DELETE_INGRIDIENTS = 'DELET_INGRIDIENTS';
export const SET_ORDER = 'SET_ORDER';
export const CHECK_VIEWE_INGRIDIENTS = 'CHECK_VIEWE_INGRIDIENTS';
export const CLEAR_VIEWE_INGRIDIENTS = 'CLEAR_VIEWE_INGRIDIENTS';
